# Generated by Django 5.1.3 on 2024-11-22 09:13

import bank_api.money_field
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StyleBankClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('family_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'client of the bank',
                'verbose_name_plural': 'clients of the bank',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StyleBankValute',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'valute',
                'verbose_name_plural': 'valutes',
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StyleBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', bank_api.money_field.MoneyField()),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='style_bank.stylebankclient')),
                ('valute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='style_bank.stylebankvalute')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StyleBankLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_sum', bank_api.money_field.MoneyField()),
                ('pay_rest', bank_api.money_field.MoneyField()),
                ('monthly_pay', bank_api.money_field.MoneyField()),
                ('get_date', models.DateField()),
                ('repayment_date', models.DateField()),
                ('documents', models.TextField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='style_bank.stylebankclient')),
            ],
            options={
                'verbose_name': 'loan',
                'verbose_name_plural': 'loans',
                'ordering': ('get_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StyleBankSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('sum', bank_api.money_field.MoneyField()),
                ('category', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='style_bank.stylebankaccount')),
            ],
            options={
                'verbose_name': 'salary',
                'verbose_name_plural': 'salaries',
                'ordering': ('date_time',),
                'abstract': False,
            },
        ),
    ]
