version: "3.1"

services:

  db:
    restart: always
    image: postgres
    container_name: django-openapi
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: ./config/
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8090"
    volumes:
      - ./config/:/app
    depends_on:
      - db
  nginx:
     build: ./nginxbuilder/
     ports:
      - 80:80
      - 443:443
    restart: always
     depends_on:
      - db
      - web
    volumes:
      - ./certbot/www/:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
volumes:
  postgres_data:
