version: "3.1"

services:

  db:
    build: ./postgres/
    restart: always
    image: postgres
    container_name: django-openapi
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_EBANK_NAME=ebank
      - POSTGRES_STYLEBANK_NAME=stylebank
      - POSTGRES_CONSENT_NAME=consent
      - POSTGRES_PORT=5432
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql@17/data/

  web:
    build: ./config/
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    volumes:
      - ./config/:/app
    ports:
      - "80:80"
    depends_on:
      - db
volumes:
  postgres_data: