# Generated by Django 5.1.3 on 2024-11-21 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hob_api', '0002_remove_valute_id_alter_valute_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBankAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hob_api.account')),
            ],
            bases=('hob_api.account',),
        ),
        migrations.CreateModel(
            name='EBankClient',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hob_api.client')),
            ],
            bases=('hob_api.client',),
        ),
        migrations.CreateModel(
            name='EBankLoan',
            fields=[
                ('loan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hob_api.loan')),
            ],
            bases=('hob_api.loan',),
        ),
        migrations.CreateModel(
            name='EBankSalary',
            fields=[
                ('salary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hob_api.salary')),
            ],
            bases=('hob_api.salary',),
        ),
        migrations.CreateModel(
            name='EBankValute',
            fields=[
                ('valute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hob_api.valute')),
            ],
            bases=('hob_api.valute',),
        ),
    ]
