# Generated by Django 5.1.3 on 2024-11-10 08:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=255)),
                ('organizations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('agreement', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'consent',
                'verbose_name_plural': 'consents',
                'ordering': ('zone', 'agreement'),
            },
        ),
    ]
