# Generated by Django 5.1.3 on 2024-11-21 01:06

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'operation type',
                'verbose_name_plural': 'operation types',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('expire_date_time', models.DateTimeField(default=datetime.datetime(2024, 11, 22, 1, 6, 10, 616176))),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expire_date_time', models.DateTimeField()),
                ('agent', models.UUIDField()),
                ('contragent', models.UUIDField()),
                ('agreement', models.BooleanField(default=False)),
                ('expire_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consent_service.transaction')),
            ],
            options={
                'verbose_name': 'consent',
                'verbose_name_plural': 'consents',
            },
        ),
        migrations.CreateModel(
            name='AtomicOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Created'), (1, 'In progress'), (2, 'Commited'), (3, 'Rolled')], default=0, editable=False)),
                ('last_state_date_time', models.DateTimeField(auto_now=True)),
                ('agent', models.UUIDField()),
                ('contragent', models.UUIDField()),
                ('details', models.JSONField()),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='consent_service.operationtype')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='consent_service.transaction')),
            ],
            options={
                'verbose_name': 'atomic operation',
                'verbose_name_plural': 'atomic operations',
                'order_with_respect_to': 'transaction',
            },
        ),
    ]
