# Generated by Django 5.1.3 on 2024-11-22 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent_service', '0002_alter_transaction_expire_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expire_date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 23, 9, 43, 26, 11882)),
        ),
    ]
