# Generated by Django 5.1.3 on 2024-11-22 09:56

import consent_service.transaction_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent_service', '0003_alter_transaction_expire_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expire_date_time',
            field=models.DateTimeField(default=consent_service.transaction_model.Transaction.default_date_time),
        ),
    ]
