# Generated by Django 5.1.3 on 2024-11-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent_service', '0004_alter_transaction_expire_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
