# Generated by Django 5.1.3 on 2024-11-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent_service', '0005_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
