# Generated by Django 5.1.3 on 2024-11-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent_service', '0011_agent_api_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atomicoperation',
            old_name='details',
            new_name='agent_details',
        ),
        migrations.AddField(
            model_name='atomicoperation',
            name='contragent_details',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
