# Generated by Django 5.1.3 on 2024-11-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent_service', '0012_rename_details_atomicoperation_agent_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomicoperation',
            name='agent_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atomicoperation',
            name='contragent_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
