# Generated by Django 5.1.3 on 2024-11-23 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consent_service', '0013_alter_atomicoperation_agent_details_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OperationType',
            new_name='ConsentOperattionType',
        ),
    ]
