# Generated by Django 5.1.3 on 2024-11-21 00:49

import django.db.models.deletion
import hob_api.money_field
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('family_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'client of the bank',
                'verbose_name_plural': 'clients of the bank',
            },
        ),
        migrations.CreateModel(
            name='Valute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'valute',
                'verbose_name_plural': 'valutes',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', hob_api.money_field.MoneyField()),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hob_api.client')),
                ('valute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hob_api.valute')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_sum', hob_api.money_field.MoneyField()),
                ('pay_rest', hob_api.money_field.MoneyField()),
                ('monthly_pay', hob_api.money_field.MoneyField()),
                ('get_date', models.DateField()),
                ('repayment_date', models.DateField()),
                ('documents', models.TextField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hob_api.client')),
            ],
            options={
                'verbose_name': 'loan',
                'verbose_name_plural': 'loans',
                'ordering': ('get_date',),
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('sum', hob_api.money_field.MoneyField()),
                ('category', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hob_api.account')),
            ],
            options={
                'verbose_name': 'salary',
                'verbose_name_plural': 'salaries',
                'ordering': ('date_time',),
            },
        ),
    ]
