# Generated by Django 5.1.3 on 2024-11-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hob_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=255, unique=True)),
                ('balance', models.BigIntegerField(default=0)),
                ('valute_code', models.CharField(default='ru', max_length=3)),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'ordering': ('holder_name',),
            },
        ),
    ]
