# Generated by Django 5.1.3 on 2024-11-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hob_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valute',
            name='id',
        ),
        migrations.AlterField(
            model_name='valute',
            name='code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
