# Generated by Django 5.1.3 on 2024-11-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hob_api', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('family_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
