# Generated by Django 5.1.3 on 2024-11-10 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hob_api', '0003_client_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'valute',
                'verbose_name_plural': 'valutes',
                'ordering': ('code',),
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'client of the bank', 'verbose_name_plural': 'clients of the bank'},
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hob_api.client')),
                ('valute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hob_api.valute')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
            },
        ),
    ]
