# Generated by Django 5.1.3 on 2024-11-10 07:20

import django.db.models.deletion
import hob_api.money_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hob_api', '0005_alter_client_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=hob_api.money_field.MoneyField(),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_sum', hob_api.money_field.MoneyField()),
                ('pay_rest', hob_api.money_field.MoneyField()),
                ('monthly_pay', hob_api.money_field.MoneyField()),
                ('get_date', models.DateField()),
                ('repayment_date', models.DateField()),
                ('documents', models.TextField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hob_api.client')),
            ],
            options={
                'verbose_name': 'loan ',
                'verbose_name_plural': 'loans',
            },
        ),
    ]
