# Generated by Django 5.1.3 on 2024-11-10 07:49

import django.db.models.deletion
import hob_api.money_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hob_api', '0006_alter_account_balance_loan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ('get_date',), 'verbose_name': 'loan', 'verbose_name_plural': 'loans'},
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('sum', hob_api.money_field.MoneyField()),
                ('category', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hob_api.account')),
            ],
            options={
                'verbose_name': 'salary',
                'verbose_name_plural': 'salaries',
                'ordering': ('date_time',),
            },
        ),
    ]
