# Generated by Django 5.1.3 on 2024-11-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hob_api', '0007_alter_loan_options_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
